wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.13
    start_time: 1674788468.365924
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.13.9
      8:
      - 2
      - 3
      - 5
